language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'
  - '8.1'

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install --prefer-dist --no-interaction
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test

script:
  - ./bin/phpunit -c app