<?php

namespace AntispamBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlacklistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlacklistRepository extends EntityRepository
{
 
}
