<?php

namespace AntispamBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmailBlacklistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailBlacklistRepository extends EntityRepository
{
}
