; Runtime overrides for Antispam in production
memory_limit = 256M
upload_max_filesize = 32M
post_max_size = 32M
date.timezone = UTC

opcache.enable = 1
opcache.memory_consumption = 128
opcache.max_accelerated_files = 10000
opcache.validate_timestamps = 0
