services:
#    antispam.example:
#        class: AntispamBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    antispam.connection:
        class: AntispamBundle\Services\ConnectionService
        arguments: ["@configuration"]

    antispam.inbox:
        class: AntispamBundle\Services\InboxService
        arguments: ["@antispam.connection"]

    antispam.message:
        class: AntispamBundle\Services\MessageService


    antispam.checkkonfig.listener:
        class: AntispamBundle\EventListener\CheckConfig\CheckEmailData
        arguments: ["@configuration"]
        tags:
            - { name: kernel.event_listener, event: antispam.check.config, method: CheckEmail }
            - { name: kernel.event_listener, event: antispam.check.config, method: CheckLogin }
            - { name: kernel.event_listener, event: antispam.check.config, method: CheckPass }
            - { name: kernel.event_listener, event: antispam.check.config, method: CheckImap }
            - { name: kernel.event_listener, event: antispam.check.config, method: tryToConnect }


    antispam.checkemail.listener.alreadychecked:
        class: AntispamBundle\EventListener\Message\CheckIfIsAlreadyChecked
        arguments: ["@antispam.message"]
        tags:
            - { name: kernel.event_listener, event: antispam.check.message, method: check  }

    antispam.checkemail.listener:
        class: AntispamBundle\EventListener\Message\CheckWhitelist
        arguments: ["@doctrine.orm.default_entity_manager","@antispam.message"]
        tags:
            - { name: kernel.event_listener, event: antispam.check.message, method: check  }